name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8 (adjusted for black compatibility)
      run: |
        flake8 . \
          --count \
          --select=E9,F63,F7,F82 \
          --show-source \
          --statistics \
          --max-line-length=88 \
          --extend-ignore=E203,W503
        flake8 . \
          --count \
          --exit-zero \
          --max-complexity=10 \
          --max-line-length=88 \
          --statistics \
          --extend-ignore=E203,W503

    - name: Check formatting with black
      run: |
        black . --check

    - name: Type check with mypy
      run: |
        mypy .

    - name: Run tests
      run: |
        pytest tests/

    - name: Check dependencies for vulnerabilities
      run: |
        safety check
