name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    - name: Check formatting with black
      run: |
        black . --check
    - name: Type check with mypy
      run: |
        mypy .
    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Check dependencies for vulnerabilities
      run: |
        safety check
    - name: Run security checks
      run: |
        bandit -r . -f json -o bandit-results.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 